baseURL = "https://gospel-library.netlify.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Gospel Library | Performance"

[markup.goldmark.renderer]
unsafe= true

[outputs]
page = ["json", "html"]
section = ["json", "html"]
home = ["json", "html"]

[params]
description = "The canonized scriptures of The Church of Jesus Christ of Latter-day Saints in performance benefits."
custom_js = []
custom_css = []
useSearch = false